### ISSUE TITLE
[Feature] Services 페이지 BRANDING 섹션 구현

### ISSUE THREAD

**Issue by sooyeon-kr** [pda-sooso/pda-pair-programming#4]
### Services 페이지
- [x] 섹션 구조 정의 - html
- [x] 사진 추가
- [x] 스타일 지정

구현 후 같은 스타일의 DESIGN, VIDEO, CONTENT 섹션도 구현할 것

**Comment by soyalattee** [comment]
feature/services 브랜치 생성했습니다. feature/services 브랜치에서 작업하고 main으로 풀리퀘해주세용 :)

**Comment by sooyeon-kr** [comment]
- [x] content 여백 조정
- [x] border-bottom line 굵기 조정

하여서 DESIGN, VIEDO, CONTENT 등에도 적용하면 될 것 같아요! 

![스크린샷 2024-04-23 오전 1 40 19](https://github.com/pda-sooso/pda-pair-programming/assets/39377091/116fa00d-845b-493a-9fce-ce4c208664aa)

여기까지 구현하여(미완성) 해당 브랜치에 푸시하였습니다!
